# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_xbar_1/d_xbar_1.xci
# IP: The module: 'd_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_xbar_1/d_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_xbar_1/d_xbar_1.xci
# IP: The module: 'd_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_xbar_1/d_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
