# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0.xci
# IP: The module: 'd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0.xci
# IP: The module: 'd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.srcs/sources_1/bd/d/ip/d_axi_gpio_1_0/d_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
