# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Nora/tutorial/microblaze/microblaze_tutorial.cache/wt [current_project]
set_property parent.project_path D:/Nora/tutorial/microblaze/microblaze_tutorial.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cmod_a7-15t:part0:1.1 [current_project]
set_property ip_output_repo d:/Nora/tutorial/microblaze/microblaze_tutorial.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.sdk/adc/Debug/adc.elf
set_property SCOPED_TO_REF d [get_files -all D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.sdk/adc/Debug/adc.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all D:/Nora/cmod_a7_projects/microblaze_new/microblaze_new.sdk/adc/Debug/adc.elf]
read_vhdl -library xil_defaultlib D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/hdl/d_wrapper.vhd
add_files D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/d.bd
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_microblaze_0_0/d_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_microblaze_0_0/d_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_microblaze_0_0/d_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_clk_wiz_0_0/d_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_clk_wiz_0_0/d_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_clk_wiz_0_0/d_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_dlmb_v10_0/d_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_dlmb_v10_0/d_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_ilmb_v10_0/d_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_ilmb_v10_0/d_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_dlmb_bram_if_cntlr_0/d_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_ilmb_bram_if_cntlr_0/d_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_lmb_bram_0/d_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_mdm_1_0/d_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_mdm_1_0/d_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_rst_clk_wiz_0_100M_0/d_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_rst_clk_wiz_0_100M_0/d_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_rst_clk_wiz_0_100M_0/d_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_emc_0_0/d_axi_emc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_emc_0_0/d_axi_emc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_emc_0_0/d_axi_emc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_uartlite_0_0/d_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_uartlite_0_0/d_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_uartlite_0_0/d_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_xbar_0/d_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_gpio_0_0/d_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_gpio_0_0/d_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_gpio_0_0/d_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_xbar_1/d_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_0/d_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_0/d_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_0/d_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_0/d_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_1_0/d_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_1_0/d_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_1_0/d_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_1_0/d_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_3/d_axi_quad_spi_0_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_3/d_axi_quad_spi_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_3/d_axi_quad_spi_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/ip/d_axi_quad_spi_0_3/d_axi_quad_spi_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/d_ooc.xdc]
set_property is_locked true [get_files D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/sources_1/bd/d/d.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files D:/Nora/tutorial/microblaze/microblaze_tutorial.srcs/constrs_1/new/const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top d_wrapper -part xc7a15tcpg236-1


write_checkpoint -force -noxdef d_wrapper.dcp

catch { report_utilization -file d_wrapper_utilization_synth.rpt -pb d_wrapper_utilization_synth.pb }
