# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/d/d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d || ORIG_REF_NAME==d}]

# IP: bd/d/ip/d_microblaze_0_0/d_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_0_0 || ORIG_REF_NAME==d_microblaze_0_0}]

# IP: bd/d/ip/d_clk_wiz_0_0/d_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_clk_wiz_0_0 || ORIG_REF_NAME==d_clk_wiz_0_0}]

# IP: bd/d/ip/d_dlmb_v10_0/d_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_dlmb_v10_0 || ORIG_REF_NAME==d_dlmb_v10_0}]

# IP: bd/d/ip/d_ilmb_v10_0/d_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_ilmb_v10_0 || ORIG_REF_NAME==d_ilmb_v10_0}]

# IP: bd/d/ip/d_dlmb_bram_if_cntlr_0/d_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==d_dlmb_bram_if_cntlr_0}]

# IP: bd/d/ip/d_ilmb_bram_if_cntlr_0/d_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==d_ilmb_bram_if_cntlr_0}]

# IP: bd/d/ip/d_lmb_bram_0/d_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_lmb_bram_0 || ORIG_REF_NAME==d_lmb_bram_0}]

# IP: bd/d/ip/d_mdm_1_0/d_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_mdm_1_0 || ORIG_REF_NAME==d_mdm_1_0}]

# IP: bd/d/ip/d_rst_clk_wiz_0_100M_0/d_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==d_rst_clk_wiz_0_100M_0}]

# IP: bd/d/ip/d_axi_emc_0_0/d_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_emc_0_0 || ORIG_REF_NAME==d_axi_emc_0_0}]

# IP: bd/d/ip/d_axi_uartlite_0_0/d_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_uartlite_0_0 || ORIG_REF_NAME==d_axi_uartlite_0_0}]

# IP: bd/d/ip/d_axi_mem_intercon_0/d_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_mem_intercon_0 || ORIG_REF_NAME==d_axi_mem_intercon_0}]

# IP: bd/d/ip/d_xbar_0/d_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_xbar_0 || ORIG_REF_NAME==d_xbar_0}]

# IP: bd/d/ip/d_microblaze_0_axi_periph_0/d_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_0_axi_periph_0 || ORIG_REF_NAME==d_microblaze_0_axi_periph_0}]

# IP: bd/d/ip/d_axi_gpio_0_0/d_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_gpio_0_0 || ORIG_REF_NAME==d_axi_gpio_0_0}]

# IP: bd/d/ip/d_xbar_1/d_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_xbar_1 || ORIG_REF_NAME==d_xbar_1}]

# IP: bd/d/ip/d_axi_quad_spi_0_0/d_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_quad_spi_0_0 || ORIG_REF_NAME==d_axi_quad_spi_0_0}]

# IP: bd/d/ip/d_axi_quad_spi_1_0/d_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_quad_spi_1_0 || ORIG_REF_NAME==d_axi_quad_spi_1_0}]

# IP: bd/d/ip/d_axi_quad_spi_0_3/d_axi_quad_spi_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_axi_quad_spi_0_3 || ORIG_REF_NAME==d_axi_quad_spi_0_3}]

# XDC: bd/d/d_ooc.xdc
