webtalk_init -webtalk_dir D:\\Nora\\tutorial\\microblaze\\microblaze_tutorial.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2016-12-18 14:57:17" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8vvh3sseaoj216g0fs9dc2ccbg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_35" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1482056087044" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.3" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key Device -value "7a15t" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1482056087044"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key DebugCount -value "12" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1482065837532"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1482065837532"
webtalk_transmit -clientid 1675470848 -regid "" -xml D:\\Nora\\tutorial\\microblaze\\microblaze_tutorial.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Nora\\tutorial\\microblaze\\microblaze_tutorial.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Nora\\tutorial\\microblaze\\microblaze_tutorial.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
